home/urls.py
from django.urls import path, include
from django.utils.functional import new_method_proxy

from .  import views

app_name = 'home'

urlpatterns = [
    
    path('', views.metheqq_nile, name='home'),
    path('shop/', views.Productlist , name="Productlist"),
    path('item/<slug:slug>/', views.Product_detale , name="product_detail"),
    path('item/<slug:slug>/<int:marketerid>/', views.Product_detale2 , name="product_detail"),
    path('search/<slug:catgory_slug>/', views.catogrey_list , name='catogrey_list')
] 

metheqq_root/urls.py
from django.contrib.auth import views as auth_views
from unicodedata import name
from django.views.generic import TemplateView
from django.urls import path, include
from .froms import (UserLoginForm, PwdResetForm ,PwdResetConfirmForm)
from .  import views


app_name = 'metheqq_root'

urlpatterns = [
    path('', views.campany),
    path('login/', auth_views.LoginView.as_view(template_name='metheqq_root/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('cheekpage/', views.Cheekpage ,name='cheekpage'),
    path('cheek/', views.Cheek , name='cheek'),
    path('packects/', views.packects, name='packects'),
    path('register/', views.account_register , name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('pay/', views.pay_pakect , name='pay'),
    path('pay2/', views.pay_pakect2 , name='pay2'),
    path('dashboard/', views.dashboard , name='dashboard'),
    path('profile/edit/', views.edit_details , name='edit_details'),
    path('profile/delete_user/', views.delete_user , name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="metheqq_root/user/delete_confirm.html"), name='delete_confirmation'),
]

mitheqq/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import urls

import metheqq_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('metheqq_root.urls', namespace='meheqq_root')),
    path('market/', include('home.urls', namespace='home')),
    path('basket', include('basket.urls', namespace='basket')),
    path('account/', include('acount.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:

  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metheqq_root/models.py
from django.db import models
from acount.models import UserBase
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)
from random import randrange



CHARSET = '0123456789'
LENGTH = 4
MAX_TRIES = 32




class Marketers(models.Model):
    
    user = models.ForeignKey(UserBase, on_delete=models.CASCADE)
    refrens = models.CharField(max_length=255, editable=True, unique=True, blank=True)
   

    is_tts = models.BooleanField(default=False)
    is_ts =  models.BooleanField(default=False)

    
    def save(self, *args, **kwargs):
        """
        Upon saving, generate a code by randomly picking LENGTH number of
        characters from CHARSET and concatenating them. If code has already
        been used, repeat until a unique code is found, or fail after trying
        MAX_TRIES number of times. (This will work reliably for even modest
        values of LENGTH and MAX_TRIES, but do check for the exception.)
        Discussion of method: http://stackoverflow.com/questions/2076838/
        """
        loop_num = 0
        unique = False
        while not unique:
            if loop_num < MAX_TRIES:
                new_code = 'MQ'
                for i in range(LENGTH): # TODO: change to xrange() for python 2
                    new_code += CHARSET[randrange(0, len(CHARSET))]
                if not Marketers.objects.filter(refrens=new_code):
                    self.refrens = new_code
                    unique = True
                loop_num += 1
            else:
                raise ValueError("Couldn't generate a unique code.")
        super(Marketers, self).save(*args, **kwargs)
    
    

    def __str__(self):
        return self.user.user_name
    
class MarketersComisions(models.Model):
    marketers = models.ForeignKey(Marketers, on_delete=models.CASCADE, related_name='comisions')
    comisions =  models.FloatField()
    
    def __str__(self):
        return self.marketers.refrens 
    
    
class Ecard(models.Model):
    ecard = models.CharField(max_length=255, editable=True, unique=True, blank=True)
    is_use = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):
        """
        Upon saving, generate a code by randomly picking LENGTH number of
        characters from CHARSET and concatenating them. If code has already
        been used, repeat until a unique code is found, or fail after trying
        MAX_TRIES number of times. (This will work reliably for even modest
        values of LENGTH and MAX_TRIES, but do check for the exception.)
        Discussion of method: http://stackoverflow.com/questions/2076838/
        """
        loop_num = 0
        unique = False
        while not unique:
            if loop_num < MAX_TRIES:
                new_code = 'EC'
                for i in range(LENGTH): # TODO: change to xrange() for python 2
                    new_code += CHARSET[randrange(0, len(CHARSET))]
                if not Ecard.objects.filter(ecard=new_code):
                    self.ecard = new_code
                    unique = True
                loop_num += 1
            else:
                raise ValueError("Couldn't generate a unique code.")
        super(Ecard, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.ecard    
        
# Create your models here.
class Campany(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    class Meta:
        verbose_name_plural = 'Campany'

    def get_absolute_url(self):
        return reverse("metheqq_root:campany_list", args=[self.slug])

    def __str__(self):
        return self.name


class MangerWord(models.Model):
    name = models.CharField(max_length=100)
    iamge = models.ImageField()
    word = models.TextField(max_length=255)
    postion = models.CharField(max_length=100)
    
    
    def __str__(self):
        return self.name

metheqq_root/views.py
from queue import Empty
from turtle import update
from unicodedata import decimal
from django.shortcuts import render, get_object_or_404,redirect
from django.http.response import JsonResponse
from django.contrib.auth import login, logout
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.conf import settings
from django.http import HttpResponse
from .froms import RegistrtaionForm, UserEditForm
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from acount.token import account_activation_token
from acount.models import UserBase
from .models import Campany,MangerWord,Marketers,MarketersComisions,Ecard
from acount import froms


# Create your views here.
def campany(request):
        companys = Campany.objects.all()
        mange = MangerWord.objects.all()
        contaxt = {
            'campany': companys,
            'mange': mange
        }
        return render(request, 'metheqq_root/index.html', contaxt)


def SenEmail(request):
    pass


@login_required
def Cheekpage(request):
    return render(request, 'metheqq_root/refrence/ref.html')



@login_required
def Cheek(request):
    if request.method == 'POST':
        ref_key = request.POST.get('ref')
        packects = request.POST.get('packects')
        packectssrt = request.POST.get('packectssrt')
        print(type(packects))
        print(ref_key)
        print(packectssrt)
        
        if Marketers.objects.filter(refrens=ref_key).exists:
            mark = get_object_or_404(Marketers,refrens=ref_key)
            print(mark)
            mard_id = mark.id
            print(mard_id)
            markcom = get_object_or_404(MarketersComisions,marketers=mard_id)
            print(markcom)
            markcom.comisions += ((float(packects) * 2 ) / 100)
            markcom.save()
            xxxx = mark.user 
            print(xxxx)
            data = { 
                    'is_taken': xxxx.first_name
                }
        else:
            print('sooory')
     
    return JsonResponse(data)



def packects(request):
    return render(request, 'metheqq_root/packects/page.html')



def account_register(request):
    if request.method == 'POST':
        registerfrom = RegistrtaionForm(request.POST)
        print(registerfrom)
        if registerfrom.is_valid():
            user = registerfrom.save(commit=False)
            user.first_name = registerfrom.cleaned_data['first_name']
            user.email = registerfrom.cleaned_data['email']
            user.set_password(registerfrom.cleaned_data['password'])
            user.is_active = False
            user.save()
            uaser = Marketers.objects.create(user=user,  is_tts=False, is_ts= False)
            MarketersComisions.objects.create(marketers=uaser, comisions=0)
            current_site = get_current_site(request)
            subject = 'Activate youer Account'
            message = render_to_string('metheqq_root/registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject=subject, message=message)
            return HttpResponse('تم التسجيل ب نجاح')
    else:
        registerfrom = RegistrtaionForm()

    return render(request, 'metheqq_root/registration/register.html', {'form': registerfrom})

def account_activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = UserBase.objects.get(pk=uid)
    except:
        pass
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user) 
        return redirect('metheqq_root:cheekpage')
    else:
        return render(request, 'account/registration/activation_invalid.html')

@login_required
def pay_pakect(request):
    return render (request, 'metheqq_root/pay/pay.html')

@login_required
def pay_pakect2(request):    
    if request.method == 'POST':
        code = request.POST.get('code')
        print(code)
        
        if Ecard.objects.filter(ecard=code).exists():
            code2 = get_object_or_404(Ecard, ecard=code, is_use=False)
            print(code2)
            code2.is_use = True
            code2.save()
           
            
    return JsonResponse({'code': 'sussus'})
    
@login_required
def dashboard(request):
    return render(request, 'metheqq_root/user/dashboard.html')


@login_required
def edit_details(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)

    return render(request, 'metheqq_root/user/edit_details.html', {'user_form': user_form})


@login_required
def delete_user(request):
    user = UserBase.objects.get(user_name=request.user)
    user.is_active = False
    user.save()
    logout(request)
    return redirect('metheqq_root:delete_confirmation')

templates/metheqq_root/refrence/ref.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mithaqq</title>
  <link rel="stylesheet" href="{% static 'metheqq_root/assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'metheqq_root/assets/css/fontawesome.css' %}">
  <link rel="stylesheet" href="{% static 'metheqq_root/assets/css/glightbox.min.css' %}" />
  <link rel="stylesheet" href="{% static 'metheqq_root/slick/slick/slick.css' %}"/>
  <link rel="stylesheet" href="{% static 'metheqq_root/slick/slick/slick-theme.css' %}"/>
  <script src="{% static 'metheqq_root/assets/js/glightbox.min.js' %}"></script>
  <script src="{% static 'metheqq_root/assets/js/index.js' %}"></script>


  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lateef&display=swap" rel="stylesheet"> 


  <style>
    .account-form input
    {
    border: 2px solid #ccc;
    height: calc(2em + .75rem + 2px);
  }

  .form-control {
    border: 2px solid #ccc;
  }

  .account-form input:focus {
    border-color: #1497ff;
    box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
  }
  #cont{
    color: black;
      text-decoration: none;
      font-family: 'Lateef', cursive;
      font-weight: 700;
  }
    .sub{
        text-align: right !important;
    }
    #map {
      min-width: 300px;
      min-height: 232px;
      width: 100%;
      height: 69%;
    }

    .header {
        background-color: #F5F5F5;
        color: #36A0FF;
        height: 70px;
        font-size: 27px;
        padding: 10px;
        text-align: right !important;
    }
    .panel-body{
        text-align: right !important;
    }
</style>
</head>
<body>
<!-- ////////////////////////////////////////////////////////////////////////////////////////
                               START SECTION 1 - THE NAVBAR SECTION  
/////////////////////////////////////////////////////////////////////////////////////////////-->
<nav class="navbar navbar-expand-lg navbar-dark menu shadow fixed-top">
    <div class="container">
      <a class="navbar-brand" href="">
        <img src="{% static 'metheqq_root/images/IMG-20211223-WA0000.jpg' %}" alt="logo image">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">الرئيسة</a></li>
          <li class="nav-item"><a class="nav-link" href="#services">من نحن</a></li>
          <li class="nav-item"><a class="nav-link" href="#testimonials">المدراء</a></li>
          <li class="nav-item"><a class="nav-link" href="#faq">خدماتنا</a></li>
          <li class="nav-item"><a class="nav-link" href="#portfolio">شركاتنا</a></li>
          <li class="nav-item"><a class="nav-link" href="#contact">اتصل بنا</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<div class="container-fluid dir" style="padding-top:100px ; background-color:rgb(17, 16, 16, 0.95)">
  <div class="row no-gutter">
    <div class="col-md-12">
      <div class="login d-flex align-items-center py-5" style="width: 100%;">
        <div class="container">
          <div class="row">
              <form>
                <div class="row g-3">
                <div id="show"  >
                <label for="card-element" style="padding-bottom: 25px;"> المرجع</label>
                  <input type="text" class="form-control" id="ref_code" placeholder="ادخل كود المرجع " >
                  <h1>أكـــــــــــــــــــــد الباقــــــــــة</h1>
                  <select name="packects_select" id="packects" style="margin-top: 15px; width:100%">
                    <option value="10.9">tts</option>
                    <option value="5.9">ts</option>
                  </select>
                </div>
                <hr class="my-4">

                <button  id="submit" class="btn btn-primary w-100 fw-bold" style="color: black;">ادخل</button>
              </form>
              <div id="sucss" class="alert alert-primary" role="alert" style="display: none;">
                
              </div>
              <a  id="cont" href="{% url 'metheqq_root:pay' %}?" style="display: none; color:black !important">استمرار</a>
              <div id="notsucss" class="alert alert-warning" role="alert" style="display: none;">
               
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script  src="{% static 'metheqq_root/assets/vendors/js/glightbox.min.js' %}"></script>  
<script  src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script  src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script  src="{% static 'metheqq_root/slick/slick/slick.min.js' %}"></script>
<script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbWzQbvTnAdhcRUr4wZa3BOfAnDjaQWWk&callback=initMap"async></script>


<script type="text/javascript">
      const lightbox = GLightbox({
        'touchNavigation': true,
        'href': 'https://mithaqq.herokuapp.com/static/metheqq_root/images/mithaqq.mp4',
        'type': 'video',
        'source': 'local', //vimeo, youtube or local
        'width': 900,
        'autoPlayVideos': 'true',
});



  $(document).on('click', '#submit', function (e){
      e.preventDefault(); 
      $.ajax({
        type: 'POST',
        url: '{% url "metheqq_root:cheek" %}',
        data: {
            ref: $('#ref_code').val(),
            packects:$('#packects option:selected').val(),
            packectssrt:$('#packects option:selected').text(),
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
        },
        success: function (json){
          if(json.is_taken){
            document.getElementById('sucss').style = 'black'
            document.getElementById('sucss').innerHTML = 'المرجع هوو ' + json.is_taken
            document.getElementById('cont').style = 'black'
          }
          if(json.is_nottaken){
            document.getElementById('notsucss').style = 'black'
            document.getElementById('notsucss').innerHTML =   json.is_nottaken
          }
        },
        error: function (xhr, errmsg , err){}
      });
    });


$(document).ready(function(){
  $('.youerclass').slick({
      dots: true,
      autoplay:true,
      centerMode: true,
      centerPadding: '60px',
      slidesToShow: 3,
      responsive: [
        {
          breakpoint: 768,
          settings: {
            arrows: false,
            centerMode: true,
            centerPadding: '40px',
            slidesToShow: 3
          }
        },
        {
          breakpoint: 480,
          settings: {
            arrows: false,
            centerMode: true,
            centerPadding: '40px',
            slidesToShow: 1
          }
        }
      ]
  });

});

function videoUrl(hmmmmm){
  document.getElementById('vidslid').src = hmmmmm;
}
</script>
     <script src="{% static 'metheqq_root/assets/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html> 