acount/urls.py
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.urls import path

from .froms import (UserLoginForm, PwdResetForm ,PwdResetConfirmForm)


from . import views



app_name = 'account'

 
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register , name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm) , name='password_reset_confirm'),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # user dashboard
    path('dashboard/', views.dashboard , name='dashboard'),
    path('profile/edit/', views.edit_details , name='edit_details'),
    path('profile/delete_user/', views.delete_user , name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),

]

home/urls.py
from django.urls import path, include
from django.utils.functional import new_method_proxy

from .  import views

app_name = 'home'

urlpatterns = [
    
    path('', views.metheqq_nile, name='home'),
    path('shop/', views.Productlist , name="Productlist"),
    path('item/<slug:slug>/', views.Product_detale , name="product_detail"),
    path('item/<slug:slug>/<int:marketerid>/', views.Product_detale2 , name="product_detail"),
    path('search/<slug:catgory_slug>/', views.catogrey_list , name='catogrey_list')
] 

metheqq_root/urls.py
from django.contrib.auth import views as auth_views
from unicodedata import name
from django.views.generic import TemplateView
from django.urls import path, include
from .froms import (UserLoginForm, PwdResetForm ,PwdResetConfirmForm)
from .  import views


app_name = 'metheqq_root'

urlpatterns = [
    path('', views.campany),
    path('login/', auth_views.LoginView.as_view(template_name='metheqq_root/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('cheekpage/', views.Cheekpage ,name='cheekpage'),
    path('cheek/', views.Cheek , name='cheek'),
    path('packects/', views.packects, name='packects'),
    path('register/', views.account_register , name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('pay/', views.pay_pakect , name='pay'),
    path('pay2/', views.pay_pakect2 , name='pay2'),
    path('dashboard/', views.dashboard , name='dashboard'),
    path('profile/edit/', views.edit_details , name='edit_details'),
    path('profile/delete_user/', views.delete_user , name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="metheqq_root/user/delete_confirm.html"), name='delete_confirmation'),
]

mitheqq/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import urls

import metheqq_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('metheqq_root.urls', namespace='meheqq_root')),
    path('market/', include('home.urls', namespace='home')),
    path('basket', include('basket.urls', namespace='basket')),
    path('account/', include('acount.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:

  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metheqq_root/models.py
from django.db import models
from acount.models import UserBase
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)
from random import randrange



CHARSET = '0123456789'
LENGTH = 4
MAX_TRIES = 32




class Marketers(models.Model):
    
    user = models.ForeignKey(UserBase, on_delete=models.CASCADE)
    refrens = models.CharField(max_length=255, editable=True, unique=True, blank=True)
   

    is_tts = models.BooleanField(default=False)
    is_ts =  models.BooleanField(default=False)

    
    def save(self, *args, **kwargs):
        """
        Upon saving, generate a code by randomly picking LENGTH number of
        characters from CHARSET and concatenating them. If code has already
        been used, repeat until a unique code is found, or fail after trying
        MAX_TRIES number of times. (This will work reliably for even modest
        values of LENGTH and MAX_TRIES, but do check for the exception.)
        Discussion of method: http://stackoverflow.com/questions/2076838/
        """
        loop_num = 0
        unique = False
        while not unique:
            if loop_num < MAX_TRIES:
                new_code = 'MQ'
                for i in range(LENGTH): # TODO: change to xrange() for python 2
                    new_code += CHARSET[randrange(0, len(CHARSET))]
                if not Marketers.objects.filter(refrens=new_code):
                    self.refrens = new_code
                    unique = True
                loop_num += 1
            else:
                raise ValueError("Couldn't generate a unique code.")
        super(Marketers, self).save(*args, **kwargs)
    
    

    def __str__(self):
        return self.user.user_name
    
class MarketersComisions(models.Model):
    marketers = models.ForeignKey(Marketers, on_delete=models.CASCADE, related_name='comisions')
    comisions =  models.FloatField()
    
    def __str__(self):
        return self.marketers.refrens 
    
    
class Ecard(models.Model):
    ecard = models.CharField(max_length=255, editable=True, unique=True, blank=True)
    is_use = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):
        """
        Upon saving, generate a code by randomly picking LENGTH number of
        characters from CHARSET and concatenating them. If code has already
        been used, repeat until a unique code is found, or fail after trying
        MAX_TRIES number of times. (This will work reliably for even modest
        values of LENGTH and MAX_TRIES, but do check for the exception.)
        Discussion of method: http://stackoverflow.com/questions/2076838/
        """
        loop_num = 0
        unique = False
        while not unique:
            if loop_num < MAX_TRIES:
                new_code = 'EC'
                for i in range(LENGTH): # TODO: change to xrange() for python 2
                    new_code += CHARSET[randrange(0, len(CHARSET))]
                if not Ecard.objects.filter(ecard=new_code):
                    self.ecard = new_code
                    unique = True
                loop_num += 1
            else:
                raise ValueError("Couldn't generate a unique code.")
        super(Ecard, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.ecard    
        
# Create your models here.
class Campany(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    class Meta:
        verbose_name_plural = 'Campany'

    def get_absolute_url(self):
        return reverse("metheqq_root:campany_list", args=[self.slug])

    def __str__(self):
        return self.name


class MangerWord(models.Model):
    name = models.CharField(max_length=100)
    iamge = models.ImageField()
    word = models.TextField(max_length=255)
    postion = models.CharField(max_length=100)
    
    
    def __str__(self):
        return self.name

metheqq_root/views.py
from queue import Empty
from turtle import update
from unicodedata import decimal
from django.shortcuts import render, get_object_or_404,redirect
from django.http.response import JsonResponse
from django.contrib.auth import login, logout
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.conf import settings
from django.http import HttpResponse
from .froms import RegistrtaionForm, UserEditForm
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from acount.token import account_activation_token
from acount.models import UserBase
from .models import Campany,MangerWord,Marketers,MarketersComisions,Ecard
from acount import froms


# Create your views here.
def campany(request):
        companys = Campany.objects.all()
        mange = MangerWord.objects.all()
        contaxt = {
            'campany': companys,
            'mange': mange
        }
        return render(request, 'metheqq_root/index.html', contaxt)


def SenEmail(request):
    pass


@login_required
def Cheekpage(request):
    return render(request, 'metheqq_root/refrence/ref.html')



@login_required
def Cheek(request):
    if request.method == 'POST':
        ref_key = request.POST.get('ref')
        packects = request.POST.get('packects')
        packectssrt = request.POST.get('packectssrt')
        print(type(packects))
        print(ref_key)
        print(packectssrt)
        
        if Marketers.objects.filter(refrens=ref_key).exists:
            mark = get_object_or_404(Marketers,refrens=ref_key)
            print(mark)
            mard_id = mark.id
            print(mard_id)
            markcom = get_object_or_404(MarketersComisions,marketers=mard_id)
            print(markcom)
            markcom.comisions += ((float(packects) * 2 ) / 100)
            markcom.save()
            xxxx = mark.user 
            print(xxxx)
            data = { 
                    'is_taken': xxxx.first_name
                }
        else:
            print('sooory')
     
    return JsonResponse(data)



def packects(request):
    return render(request, 'metheqq_root/packects/page.html')



def account_register(request):
    if request.method == 'POST':
        registerfrom = RegistrtaionForm(request.POST)
        print(registerfrom)
        if registerfrom.is_valid():
            user = registerfrom.save(commit=False)
            user.first_name = registerfrom.cleaned_data['first_name']
            user.email = registerfrom.cleaned_data['email']
            user.set_password(registerfrom.cleaned_data['password'])
            user.is_active = False
            user.save()
            uaser = Marketers.objects.create(user=user,  is_tts=False, is_ts= False)
            MarketersComisions.objects.create(marketers=uaser, comisions=0)
            current_site = get_current_site(request)
            subject = 'Activate youer Account'
            message = render_to_string('metheqq_root/registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject=subject, message=message)
            return HttpResponse('تم التسجيل ب نجاح')
    else:
        registerfrom = RegistrtaionForm()

    return render(request, 'metheqq_root/registration/register.html', {'form': registerfrom})

def account_activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = UserBase.objects.get(pk=uid)
    except:
        pass
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user) 
        return redirect('metheqq_root:cheekpage')
    else:
        return render(request, 'account/registration/activation_invalid.html')

@login_required
def pay_pakect(request):
    return render (request, 'metheqq_root/pay/pay.html')

@login_required
def pay_pakect2(request):    
    if request.method == 'POST':
        code = request.POST.get('code')
        print(code)
        
        if Ecard.objects.filter(ecard=code).exists():
            code2 = get_object_or_404(Ecard, ecard=code, is_use=False)
            print(code2)
            code2.is_use = True
            code2.save()
           
            
    return JsonResponse({'code': 'sussus'})
    
@login_required
def dashboard(request):
    return render(request, 'metheqq_root/user/dashboard.html')


@login_required
def edit_details(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)

    return render(request, 'metheqq_root/user/edit_details.html', {'user_form': user_form})


@login_required
def delete_user(request):
    user = UserBase.objects.get(user_name=request.user)
    user.is_active = False
    user.save()
    logout(request)
    return redirect('metheqq_root:delete_confirmation')

templates/metheqq_root/user/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mithaqq</title>
  <link rel="stylesheet" href="{% static 'metheqq_root/assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'metheqq_root/assets/css/fontawesome.css' %}">
  <link rel="stylesheet" href="{% static 'metheqq_root/assets/css/glightbox.min.css' %}" />
  <link rel="stylesheet" href="{% static 'metheqq_root/slick/slick/slick.css' %}"/>
  <link rel="stylesheet" href="{% static 'metheqq_root/slick/slick/slick-theme.css' %}"/>
  <script src="{% static 'metheqq_root/assets/js/glightbox.min.js' %}"></script>
  <script src="{% static 'metheqq_root/assets/js/index.js' %}"></script>


  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lateef&display=swap" rel="stylesheet"> 


  <style>
   
  
    .sub{
        text-align: right !important;
    }
    #map {
      min-width: 300px;
      min-height: 232px;
      width: 100%;
      height: 69%;
    }

    .header {
        background-color: #F5F5F5;
        color: #36A0FF;
        height: 70px;
        font-size: 27px;
        padding: 10px;
        text-align: right !important;
    }
    .panel-body{
        text-align: right !important;
    }
</style>
</head>
<body style="background-color: rgb(20, 20, 20);">
<!-- ////////////////////////////////////////////////////////////////////////////////////////
                               START SECTION 1 - THE NAVBAR SECTION  
/////////////////////////////////////////////////////////////////////////////////////////////-->
<nav class="navbar navbar-expand-lg navbar-dark menu shadow fixed-top" >
    <div class="container">
      <a class="navbar-brand" href="">
        <img src="{% static 'metheqq_root/images/IMG-20211223-WA0000.jpg' %}" alt="logo image">
        <a class="login">
          <i class="fa fa-shopping-cart">
          </i><span>تسوق</span>
        </a>
        <a href="{% url 'metheqq_root:dashboard' %}" class="login">
          <i class="fas fa-user"></i>
          <span>الحساب</span>
        </a>
        {% if user.is_authenticated %}
        <a class="login" href="{% url 'metheqq_root:logout' %}">
          <i class="fas fa-door-closed"></i>
          <span> خروج </span>   
        </a>
        {% else %}
        <a href="{% url 'metheqq_root:login' %}" class="login">
          <i class="fas fa-door-open"></i>
          <span> دخول </span>
        </a>
        {% endif %}
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">الرئيسة</a></li>
          <li class="nav-item"><a class="nav-link" href="#services">من نحن</a></li>
          <li class="nav-item"><a class="nav-link" href="#testimonials">المدراء</a></li>
          <li class="nav-item"><a class="nav-link" href="#faq">خدماتنا</a></li>
          <li class="nav-item"><a class="nav-link" href="#portfolio">شركاتنا</a></li>
          <li class="nav-item"><a class="nav-link" href="#contact">اتصل بنا</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

   <main class="pt-5 dir" style="margin-top: 100px;">
       <div class="container" style="max-width: 1000px">
           <div class="col-12">
                <h1 style="color: #cd801d;" class="h2">صفحتك الشخصية</h1>
           </div>
           <div class="col-12 d-flex justify-content-between">
               <div style="color: #cd801d;">تعرف علي <span> مبيعاتك </span>  ومعلوماتك الشخصية </div>
               <div><a style="color: #cd801d;" href="{% url 'metheqq_root:edit_details' %}">تغير التفاصيل</a></div>
           </div>
        <hr />
       </div>
       <div class="container dir" style="max-width: 1000px">
   

       </div>
   </main>


   <script  src="{% static 'metheqq_root/assets/vendors/js/glightbox.min.js' %}"></script>  
   <script  src="//code.jquery.com/jquery-1.11.0.min.js"></script>
   <script  src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
   <script  src="{% static 'metheqq_root/slick/slick/slick.min.js' %}"></script>
   <script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbWzQbvTnAdhcRUr4wZa3BOfAnDjaQWWk&callback=initMap"async></script>
   
   
   <script type="text/javascript">
         const lightbox = GLightbox({
           'touchNavigation': true,
           'href': 'https://mithaqq.herokuapp.com/static/metheqq_root/images/mithaqq.mp4',
           'type': 'video',
           'source': 'local', //vimeo, youtube or local
           'width': 900,
           'autoPlayVideos': 'true',
   });
   
   $(document).ready(function(){
     $('.youerclass').slick({
         dots: true,
         autoplay:true,
         centerMode: true,
         centerPadding: '60px',
         slidesToShow: 3,
         responsive: [
           {
             breakpoint: 768,
             settings: {
               arrows: false,
               centerMode: true,
               centerPadding: '40px',
               slidesToShow: 3
             }
           },
           {
             breakpoint: 480,
             settings: {
               arrows: false,
               centerMode: true,
               centerPadding: '40px',
               slidesToShow: 1
             }
           }
         ]
     });
   
   });
   
   function videoUrl(hmmmmm){
     document.getElementById('vidslid').src = hmmmmm;
   }
   
       </script>
        <script src="{% static 'metheqq_root/assets/js/bootstrap.bundle.min.js' %}"></script>
   </body>
   </html> 

templates/metheqq_root/user/password_reset_confirm.html
{% extends "../../home/base.html" %}
{% block title %}Log-in{% endblock %}
{% block contant %}

{% if request.user.is_authenticated %}
<script>
    window.location.href = '{% url "account:dashboard" %}';
</script>
{% endif %}

<style>
 
    body {
        margin-bottom: 0px;
    }

    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-6 bg-light">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-12 mx-auto">

                            <form class="login-form p-4 rounded" method="post">
                                {% csrf_token %}
                                <h1 class="h4 mb-4 font-weight-bold">Change your password</h1>
                                <p>Use the form below to change your password.</p>

                                {% if form.errors %}
                                <div class="alert alert-primary" role="alert">
                                    Error: Please try again!
                                </div>
                                {% endif %}

                                <label class="small font-weight-bold">{{ form.new_password1.label}}</label>
                                {{ form.new_password1 }}
                                <label class="small font-weight-bold">{{ form.new_password2.label}}</label>
                                {{ form.new_password2 }}
                                <ul>
                                    <li>Your password can’t be too similar to your other personal information.</li>
                                    <li>Your password must contain at least 8 characters.</li>
                                    <li>Your password can’t be a commonly used password.</li>
                                    <li>Your password can’t be entirely numeric.</li>
                                </ul>
                                <button class="btn btn-primary btn-block py-2 mb-4 mt-5 font-weight-bold" type="submit"
                                    value="Change">Submit
                                </button>
                            </form>

                            <p class="small text-center pt-4">
                                <a href="{% url 'account:login' %}">Already have an account?</a>
                            </p>
                            <p class="small text-center">
                                <a href="{% url 'account:register' %}">Help Center?</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 d-none d-md-flex bg-image"></div>
    </div>
</div>
{% endblock %}

templates/metheqq_root/user/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'account:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/metheqq_root/user/password_reset_form.html
{% extends "../../home/base.html" %}
{% block title %}Log-in{% endblock %}
{% block contant %}

{% if request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "account:dashboard" %}';
    </script>
{% endif %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-12 mx-auto">
                            <form class="account-form p-4 rounded col-lg-8 mx-auto" method="post" action="{% url 'account:pwdreset' %}">
                                <p class="h3 mb-4 font-weight-bold">هل نسيــــت كلمــــة الســـــــر </p>
                                    <p>ادخل الايميل لارسال كلمه سر جديده</p>
                                    {% if form.errors %}
                                        <div class="alert alert-primary" role="alert">
                                            Error: Please try again!
                                        </div>
                                    {% endif %}
                                    {% csrf_token %}
                                    <label class="small font-weight-bold">{{ form.email.label}}</label>
                                    {{ form.email }}
                                    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"value="Send e-mail">ارسال الايميل</button>
                                    <p class="text-center"><a href="{% url 'account:login' %}">تسجيل الدخول </a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/metheqq_root/user/reset_status.html
{% extends "../../home/base.html" %}
{% block title %}Log-in{% endblock %}
{% block contant %}

<style>
    .container-fluid {
        max-width: 100%;
    }

    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-6  mx-auto">
                            <div class="p-4">
                                {% if 'email' in request.get_full_path %}
                                        <h3 class="mb-4">تم تغير كلمة السر بنجاح</h3>
                                        <p>افتح ايميلك واتبع الارشادات</p>
                                {% endif%}
                                {% if 'complete' in request.get_full_path %}
                                        <h3 class="mb-4">تم بنجاح تغير كلمه السر</h3>
                                        <a href="{% url 'account:login' %}">Login</a>
                                {% endif%}
                            </div>       
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}