basket/urls.py
from django.urls import path, include

from .  import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_sammary , name='basket_sammary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update')
]

home/urls.py
from django.urls import path, include
from django.utils.functional import new_method_proxy

from .  import views

app_name = 'home'

urlpatterns = [
    
    path('', views.metheqq_nile, name='home'),
    path('shop/', views.Productlist , name="Productlist"),
    path('item/<slug:slug>/', views.Product_detale , name="product_detail"),
    path('item/<slug:slug>/<int:marketerid>/', views.Product_detale2 , name="product_detail"),
    path('search/<slug:catgory_slug>/', views.catogrey_list , name='catogrey_list')
] 

mitheqq/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import urls

import metheqq_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('metheqq_root.urls', namespace='meheqq_root')),
    path('market/', include('home.urls', namespace='home')),
    path('basket', include('basket.urls', namespace='basket')),
    path('account/', include('acount.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:

  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/models.py
from django.db import models

# Create your models here.

basket/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from home.models import Product
from .basket import Basket


# Create your views here.

def basket_sammary(request):
    basket = Basket(request)
    return render(request, 'basket/sammary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        marketerid = (request.POST.get('marketerid'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty, mark=marketerid)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__();
        baskettotal = basket.get_total_price()

        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        productqty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=productqty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()

        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

templates/basket/sammary.html
{% extends "../home/base.html" %} 
{% load static %}
{% block title %}Basket Summary {% endblock title %}
{% block contant %}
  <!-- Cart Start -->
  <div class="cart-page">
    <div class="container-fluid">
        <div class="row">
          <div class="col-lg-4">
            <div class="cart-page-inner cart-page-innerme">
                <div class="row">
                    <div class="col-md-12">
                        <div class="coupon">
                            <input type="text" placeholder="ادخل الكود">
                            <button>استعمل</button>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="cart-summary">
                            <div class="cart-content">
                                <h1>ملخص السلة</h1>
                                <p>المجموع الكـلي :</p>
                                
                                <h2>الجمله:</h2>
                                <span class="" id="subtotal">{{ basket.get_total_price }}</span> 
                            </div>
                            <div class="cart-btn">
                                <a href="{% url 'payment:basket' %}"><button>ادفع</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <div class="col-lg-8">
                <div class="cart-page-inner">
                    <div class="table-responsive">
                      {% for item in basket %}
                      {% with  product=item.product  %}
                        <table data-index="{{product.id}}" class="table table-bordered tablemy product_item">
                            <thead class="thead-dark">
                                <tr>
                                    <th>المنتج</th>
                                    <th>السعر</th>
                                    <th>الكميه</th>
                                    <th>المجموع</th>
                                    <th>تعديل</th>
                                    <th>حذف</th>
                                </tr>
                            </thead>
                            <tbody class="align-middle">
                                <tr>
                                    <td>
                                        <div class="img">
                                            <a href="{{product.get_absolute_url}}"><img src="{{product.image.url}}" alt="Image"></a>
                                            <p>{{product.title|title}}</p>
                                        </div>
                                    </td>
                                    <td>SD{{product.price}}</td>
                                    <td>
                                        <select  id="select{{product.id}}">
                                          <option selected>
                                              {{item.qty}}
                                              {{item.markid}}
                                          </option>
                                          <option value="1">1</option>
                                          <option value="2">2</option>
                                          <option value="3">3</option>
                                          <option value="4">4</option>
                                          <option value="5">5</option>
                                        </select>
                                    </td>
                                    <td>SD<span id="total_price">{{item.total_price}}</span></td>
                                    <td><button id="update-button" class="update-button" data-index="{{product.id}}"><i class="fas fa-pen-alt"></i></button></td>
                                    <td><button id="delete-button" class="delete-button" data-index="{{product.id}}"><i class="fa fa-trash "></i></button></td>
                                </tr>
                            </tbody>
                        </table>
                      {% endwith %}
                      {% endfor %}
                    </div>
                </div>
            </div>
        
        </div>
    </div>
</div>

<script >
    // delete item
    $(document).on('click', '.delete-button', function (e){
        e.preventDefault(); 
        var proid = $(this).data('index');
        $.ajax({
          type: 'POST',
          url: '{% url "basket:basket_delete" %}',
          data: {
              productid: $(this).data('index'),
              csrfmiddlewaretoken: "{{csrf_token}}",
              action: 'post'
          },
          success: function (json){
              $('.product_item[data-index="'+ proid +'"]').remove();
              document.getElementById('basket-qty').innerHTML = json.qty;
              document.getElementById('subtotal').innerHTML = json.subtotal;
          },
          error: function (xhr, errmsg , err){}
        });
      });

      // update item
    $(document).on('click', '.update-button', function (e){
        e.preventDefault(); 
        var proid = $(this).data('index');
        $.ajax({
          type: 'POST',
          url: '{% url "basket:basket_update" %}',
          data: {
              productid: $(this).data('index'),
              productqty: $('#select'+ proid + ' option:selected').text(),
              csrfmiddlewaretoken: "{{csrf_token}}",
              action: 'post'
          },
          success: function (json){
            document.getElementById('basket-qty').innerHTML = json.qty;
            document.getElementById('subtotal').innerHTML = json.subtotal;
           
          },
          error: function (xhr, errmsg , err){}
        });
      })
</script>
<!-- Cart End -->
{% endblock contant %}
   